// Package wayland is partly used by code generated by `go-wl-scanner`, but also helpers for your support code.
package wayland

type Event interface {
	Proxy() Proxy
}

type EventHandlerFunc func(e Event)

type Proxy interface {
	Register(*Conn, uint32)
	Conn() *Conn
	ID() uint32

	Dispatch(msg *Message, drain chan<- Event)
	Name() string
}

type BaseProxy struct {
	conn *Conn
	id   uint32
}

func (p *BaseProxy) Register(conn *Conn, id uint32) {
	p.conn = conn
	p.id = id
}

func (p *BaseProxy) Conn() *Conn {
	return p.conn
}

func (p *BaseProxy) ID() uint32 {
	return p.id
}
