package main

import (
	"bufio"
	"bytes"
	"encoding/xml"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/spf13/pflag"
)

var (
	outputFile  = pflag.StringP("output", "o", "", "Path of the generated output go file")
	packageName = pflag.StringP("pkg", "p", "wayland_proto", "Go package name")
	runtime     = pflag.StringP("runtime", "r", "github.com/friedelschoen/wayland", "Path of the generated output go file")
	prefix      = pflag.String("strip-prefix", "", "Specifiy prefix to trim")
	suffix      = pflag.String("strip-suffix", "", "Specifiy suffix to trim")
)

type Protocol struct {
	XMLName    xml.Name    `xml:"protocol"`
	Name       string      `xml:"name,attr"`
	Copyright  string      `xml:"copyright"`
	Interfaces []Interface `xml:"interface"`
}

type Interface struct {
	XMLName     xml.Name    `xml:"interface"`
	Name        string      `xml:"name,attr"`
	Description Description `xml:"description"`
	Requests    []Request   `xml:"request"`
	Events      []Event     `xml:"event"`
	Enums       []Enum      `xml:"enum"`
	Version     int         `xml:"version,attr"`
}

type Request struct {
	XMLName     xml.Name    `xml:"request"`
	Name        string      `xml:"name,attr"`
	Type        string      `xml:"type,attr"`
	Description Description `xml:"description"`
	Args        []Arg       `xml:"arg"`
	Since       int         `xml:"since,attr"`
}

type Event struct {
	XMLName     xml.Name    `xml:"event"`
	Name        string      `xml:"name,attr"`
	Type        string      `xml:"type,attr"`
	Description Description `xml:"description"`
	Args        []Arg       `xml:"arg"`
	Since       int         `xml:"since,attr"`
}

type Enum struct {
	XMLName     xml.Name    `xml:"enum"`
	Name        string      `xml:"name,attr"`
	Description Description `xml:"description"`
	Entries     []Entry     `xml:"entry"`
	Since       int         `xml:"since,attr"`
	Bitfield    bool        `xml:"bitfield,attr"`
}

type Entry struct {
	XMLName     xml.Name    `xml:"entry"`
	Name        string      `xml:"name,attr"`
	Value       string      `xml:"value,attr"`
	Summary     string      `xml:"summary,attr"`
	Description Description `xml:"description"`
	Since       int         `xml:"since,attr"`
}

type Arg struct {
	XMLName     xml.Name    `xml:"arg"`
	Name        string      `xml:"name,attr"`
	Type        string      `xml:"type,attr"`
	Summary     string      `xml:"summary,attr"`
	Interface   string      `xml:"interface,attr"`
	Enum        string      `xml:"enum,attr"`
	Description Description `xml:"description"`
	AllowNull   bool        `xml:"allow-null,attr"`
}

type Description struct {
	XMLName xml.Name `xml:"description"`
	Text    string   `xml:",chardata"`
	Summary string   `xml:"summary,attr"`
}

func main() {
	pflag.Parse()

	var src io.ReadCloser = os.Stdin
	var srcname string
	if pflag.NArg() > 0 {
		srcname = pflag.Arg(0)
		var err error
		src, err = getInputFile(srcname)
		if err != nil {
			log.Fatalf("unable to get input file: %v", err)
		}
	}

	var protocol Protocol
	if err := xml.NewDecoder(src).Decode(&protocol); err != nil {
		log.Fatalf("unable to decode protocol xml: %v", err)
	}
	if err := src.Close(); err != nil {
		log.Printf("unable to close input file: %v", err)
	}

	var dst io.WriteCloser = os.Stdout
	if *outputFile != "" {
		var err error
		dst, err = os.Create(*outputFile)
		if err != nil {
			log.Fatalf("unable to create output file: %v", err)
		}
	}
	defer dst.Close()

	w, err := NewFormatter(dst)
	if err != nil {
		log.Printf("unable to use gofmt: %v, continuing without formatter...\n", err)
	}
	defer w.Close()

	// Header
	fmt.Fprintf(w, "// Generated by go-wayland-scanner\n")
	fmt.Fprintf(w, "// https://github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner\n")
	if srcname != "" {
		fmt.Fprintf(w, "// XML file : %s\n", srcname)
	}
	fmt.Fprintf(w, "//\n")
	fmt.Fprintf(w, "// %s Protocol Copyright: \n", protocol.Name)
	fmt.Fprint(w, comment(protocol.Copyright))
	fmt.Fprintf(w, "\n\n")
	fmt.Fprintf(w, "package %s\n", *packageName)
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "import runtime \"%s\"\n", *runtime)

	// Interfaces
	var wb bytes.Buffer
	imports := make(map[string]bool)
	for _, v := range protocol.Interfaces {
		writeInterface(&wb, imports, v)
	}

	for name, ok := range imports {
		if !ok {
			continue
		}
		fmt.Fprintf(w, "import \"%s\"\n", name)
	}
	io.Copy(w, &wb)
}

func getInputFile(file string) (io.ReadCloser, error) {
	if strings.HasPrefix(file, "http") {
		resp, err := http.Get(file)
		if err != nil {
			return nil, err
		}

		return resp.Body, nil
	}

	return os.Open(file)
}

var typeToGoTypeMap = map[string]string{
	"int":    "int32",
	"uint":   "uint32",
	"fixed":  "float64",
	"string": "string",
	"object": "Proxy",
	"array":  "[]byte",
	"fd":     "int",
}

func trimName(name string) string {
	prefixes := []string{"wl_", "xdg_"}
	duplicates := []string{"surface"}

	for _, dup := range duplicates {
		if strings.HasSuffix(name, dup) {
			return name
		}
	}

	for _, prefix := range prefixes {
		name = strings.TrimPrefix(name, prefix)
	}

	return name
}

func writeInterface(w io.Writer, imports map[string]bool, v Interface) {
	ifaceName := trimName(v.Name)
	ifaceName = toCamel(ifaceName)

	// Interface struct
	fmt.Fprintf(w, "// %s: %s\n", ifaceName, strings.Replace(v.Description.Summary, "\n", " ", -1))
	fmt.Fprint(w, comment(v.Description.Text))
	fmt.Fprintf(w, "type %s struct {\n", ifaceName)
	fmt.Fprintf(w, "ctx *runtime.Context\n")
	fmt.Fprintf(w, "id uint32\n")
	if len(v.Events) != 0 {
		fmt.Fprintf(w, "waitfor map[string]chan runtime.Event\n")
	}
	// for _, event := range v.Events {
	// 	fmt.Fprintf(w, "%sHandler %s%sHandlerFunc\n", toLowerCamel(event.Name), ifaceName, toCamel(event.Name))
	// }
	fmt.Fprintf(w, "}\n")

	// Constructor
	fmt.Fprintf(w, "// New%s: %s\n", ifaceName, strings.Replace(v.Description.Summary, "\n", " ", -1))
	fmt.Fprint(w, comment(v.Description.Text))
	fmt.Fprintf(w, "func New%s(ctx *runtime.Context) *%s {\n", ifaceName, ifaceName)
	fmt.Fprintf(w, "i := &%s{}\n", ifaceName)
	fmt.Fprintf(w, "i.ctx = ctx\n")
	fmt.Fprintf(w, "i.id = ctx.Register(i)\n")
	if len(v.Events) != 0 {
		fmt.Fprintf(w, "i.waitfor = make(map[string]chan runtime.Event)\n")
	}
	fmt.Fprintf(w, "return i\n")
	fmt.Fprintf(w, "}\n")

	fmt.Fprintf(w, "func (i *%s) Context() *runtime.Context {\n", ifaceName)
	fmt.Fprintf(w, "return i.ctx\n")
	fmt.Fprintf(w, "}\n")

	fmt.Fprintf(w, "func (i *%s) ID() uint32 {\n", ifaceName)
	fmt.Fprintf(w, "return i.id\n")
	fmt.Fprintf(w, "}\n")

	// Requests
	for i, r := range v.Requests {
		writeRequest(w, imports, ifaceName, i, r)
	}

	if !hasDestructor(v) {
		fmt.Fprintf(w, "func (i *%s) Destroy() error {\n", ifaceName)
		fmt.Fprintf(w, "i.Context().Unregister(i)\n")
		fmt.Fprintf(w, "return nil\n")
		fmt.Fprintf(w, "}\n")
	}

	// Enums
	for _, e := range v.Enums {
		writeEnum(w, ifaceName, e)
	}

	// Events
	for _, e := range v.Events {
		writeEvent(w, ifaceName, e)
	}

	// Event dispatcher
	writeEventDispatcher(w, imports, ifaceName, v)
}

func writeRequest(w io.Writer, imports map[string]bool, ifaceName string, opcode int, r Request) {
	requestName := toCamel(r.Name)

	// Generate param & returns types
	params := []string{}
	returnTypes := []string{}
	for _, arg := range r.Args {
		argNameLower := toLowerCamel(arg.Name)

		argIface := trimName(arg.Interface)
		argIface = toCamel(argIface)

		switch arg.Type {
		case "new_id":
			if arg.Interface != "" {
				returnTypes = append(returnTypes, "*"+argIface)
			} else {
				// Special for wl_registry.bind
				params = append(params, "iface string", "version uint32", "id runtime.Proxy")
			}

		case "object":
			params = append(params, argNameLower+" *"+argIface)

		case "int", "uint", "fixed",
			"string", "array", "fd":
			params = append(params, argNameLower+" "+typeToGoTypeMap[arg.Type])
		}
	}

	returnTypes = append(returnTypes, "error")

	fmt.Fprintf(w, "// %s: %s\n", requestName, strings.Replace(r.Description.Summary, "\n", " ", -1))
	fmt.Fprint(w, comment(r.Description.Text))
	fmt.Fprintf(w, "//\n")
	for _, arg := range r.Args {
		argNameLower := toLowerCamel(arg.Name)

		if arg.Summary != "" && arg.Type != "new_id" {
			fmt.Fprintf(w, "//  %s: %s\n", argNameLower, strings.Replace(arg.Summary, "\n", " ", -1))
		}
	}
	fmt.Fprintf(w, "func (i *%s) %s(%s) (%s) {\n", ifaceName, requestName, strings.Join(params, ","), strings.Join(returnTypes, ","))
	if r.Type == "destructor" {
		fmt.Fprintf(w, "defer i.Context().Unregister(i)\n")
	}

	// Create new objects, if any
	newObjects := []string{}
	for _, arg := range r.Args {
		if arg.Type == "new_id" && arg.Interface != "" {
			argNameLower := toLowerCamel(arg.Name)

			argIface := trimName(arg.Interface)
			argIface = toCamel(argIface)
			fmt.Fprintf(w, "%s := New%s(i.Context())\n", argNameLower, argIface)

			newObjects = append(newObjects, argNameLower)
		}
	}

	// Create request
	fmt.Fprintf(w, "const opcode = %d\n", opcode)

	// Calculate size
	sizes := []string{"8"}
	canBeConst := true
	for _, arg := range r.Args {
		argNameLower := toLowerCamel(arg.Name)

		switch arg.Type {
		case "new_id":
			if arg.Interface != "" {
				sizes = append(sizes, "4")
			} else {
				canBeConst = false
				fmt.Fprintf(w, "ifaceLen := runtime.PaddedLen(len(iface)+1)\n")
				sizes = append(sizes, "(4 + ifaceLen)", "4", "4")
			}

		case "object", "int", "uint", "fixed":
			sizes = append(sizes, "4")

		case "string":
			canBeConst = false
			fmt.Fprintf(w, "%sLen := runtime.PaddedLen(len(%s)+1)\n", argNameLower, argNameLower)
			sizes = append(sizes, fmt.Sprintf("(4 + %sLen)", argNameLower))

		case "array":
			canBeConst = false
			fmt.Fprintf(w, "%sLen := len(%s)\n", argNameLower, argNameLower)
			sizes = append(sizes, fmt.Sprintf("%sLen", argNameLower))
		}
	}

	if canBeConst {
		fmt.Fprintf(w, "const _reqBufLen =  %s\n", strings.Join(sizes, "+"))
		fmt.Fprintf(w, "var _reqBuf [_reqBufLen]byte\n")
	} else {
		fmt.Fprintf(w, "_reqBufLen := %s\n", strings.Join(sizes, "+"))
		fmt.Fprintf(w, "_reqBuf := make([]byte, _reqBufLen)\n")
	}

	fmt.Fprintf(w, "l := 0\n")
	fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:4], i.ID())\n")
	fmt.Fprintf(w, "l += 4\n")
	fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0xffff))\n")
	fmt.Fprintf(w, "l += 4\n")

	fdIndex := -1
	for i, arg := range r.Args {
		argNameLower := toLowerCamel(arg.Name)

		switch arg.Type {
		case "object":
			if arg.AllowNull {
				fmt.Fprintf(w, "if %s == nil {\n", argNameLower)
				fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], 0)\n")
				fmt.Fprintf(w, "l += 4\n")
				fmt.Fprintf(w, "} else {\n")
				fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], %s.ID())\n", argNameLower)
				fmt.Fprintf(w, "l += 4\n")
				fmt.Fprintf(w, "}\n")
			} else {
				fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], %s.ID())\n", argNameLower)
				fmt.Fprintf(w, "l += 4\n")
			}

		case "new_id":
			if arg.Interface != "" {
				fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], %s.ID())\n", argNameLower)
				fmt.Fprintf(w, "l += 4\n")
			} else {
				fmt.Fprintf(w, "runtime.PutString(_reqBuf[l:l+(4 + ifaceLen)], iface, ifaceLen)\n")
				fmt.Fprintf(w, "l += (4 + ifaceLen)\n")

				fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], uint32(version))\n")
				fmt.Fprintf(w, "l += 4\n")

				fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], id.ID())\n")
				fmt.Fprintf(w, "l += 4\n")
			}

		case "int", "uint":
			fmt.Fprintf(w, "runtime.PutUint32(_reqBuf[l:l+4], uint32(%s))\n", argNameLower)
			fmt.Fprintf(w, "l += 4\n")

		case "fixed":
			fmt.Fprintf(w, "runtime.PutFixed(_reqBuf[l:l+4], %s)\n", argNameLower)
			fmt.Fprintf(w, "l += 4\n")

		case "string":
			fmt.Fprintf(w, "runtime.PutString(_reqBuf[l:l+(4 + %sLen)], %s, %sLen)\n", argNameLower, argNameLower, argNameLower)
			fmt.Fprintf(w, "l += (4 + %sLen)\n", argNameLower)

		case "array":
			fmt.Fprintf(w, "runtime.PutArray(_reqBuf[l:l+(4 + %sLen)], %s)\n", argNameLower, argNameLower)
			fmt.Fprintf(w, "l += %sLen\n", argNameLower)

		case "fd":
			fdIndex = i
		}
	}

	if fdIndex != -1 {
		arg := r.Args[fdIndex]
		argNameLower := toLowerCamel(arg.Name)

		imports["syscall"] = true
		fmt.Fprintf(w, "oob := syscall.UnixRights(int(%s))\n", argNameLower)

		if canBeConst {
			fmt.Fprintf(w, "err := i.Context().WriteMsg(_reqBuf[:], oob)\n")
		} else {
			fmt.Fprintf(w, "err := i.Context().WriteMsg(_reqBuf, oob)\n")
		}
	} else {
		if canBeConst {
			fmt.Fprintf(w, "err := i.Context().WriteMsg(_reqBuf[:], nil)\n")
		} else {
			fmt.Fprintf(w, "err := i.Context().WriteMsg(_reqBuf, nil)\n")
		}
	}

	fmt.Fprintf(w, "return %s\n", strings.Join(append(newObjects, "err"), ","))
	fmt.Fprintf(w, "}\n")
}

func writeEnum(w io.Writer, ifaceName string, e Enum) {
	enumName := toCamel(e.Name)

	fmt.Fprintf(w, "type %s%s uint32\n", ifaceName, enumName)

	fmt.Fprintf(w, "// %s%s: %s\n", ifaceName, enumName, e.Description.Summary)
	fmt.Fprint(w, comment(e.Description.Text))
	fmt.Fprintf(w, "const (\n")
	for _, entry := range e.Entries {
		entryName := toCamel(entry.Name)

		if entry.Summary != "" {
			fmt.Fprintf(w, "// %s%s%s: %s\n", ifaceName, enumName, entryName, strings.Replace(entry.Summary, "\n", " ", -1))
		}
		fmt.Fprintf(w, "%s%s%s %s%s = %s\n", ifaceName, enumName, entryName, ifaceName, enumName, entry.Value)
	}
	fmt.Fprintf(w, ")\n")

	fmt.Fprintf(w, "func (e %s%s) Name() string {\n", ifaceName, enumName)
	fmt.Fprintf(w, "switch e {\n")
	for _, entry := range e.Entries {
		entryName := toCamel(entry.Name)

		fmt.Fprintf(w, "case %s%s%s:\n", ifaceName, enumName, entryName)
		fmt.Fprintf(w, "return \"%s\"\n", entry.Name)
	}
	fmt.Fprintf(w, "default:\n")
	fmt.Fprintf(w, "return \"\"\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "}\n")

	fmt.Fprintf(w, "func (e %s%s) Value() string {\n", ifaceName, enumName)
	fmt.Fprintf(w, "switch e {\n")
	for _, entry := range e.Entries {
		entryName := toCamel(entry.Name)

		fmt.Fprintf(w, "case %s%s%s:\n", ifaceName, enumName, entryName)
		fmt.Fprintf(w, "return \"%s\"\n", entry.Value)
	}
	fmt.Fprintf(w, "default:\n")
	fmt.Fprintf(w, "return \"\"\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "}\n")

	fmt.Fprintf(w, "func (e %s%s) String() string {\n", ifaceName, enumName)
	fmt.Fprintf(w, "return  e.Name() + \"=\" +  e.Value()\n")
	fmt.Fprintf(w, "}\n")
}

func writeEvent(w io.Writer, ifaceName string, e Event) {
	eventName := toCamel(e.Name)
	// eventNameLower := toLowerCamel(e.Name)

	// Event struct
	fmt.Fprintf(w, "// %s%sEvent : %s\n", ifaceName, eventName, strings.Replace(e.Description.Summary, "\n", " ", -1))
	fmt.Fprint(w, comment(e.Description.Text))
	fmt.Fprintf(w, "type %s%sEvent struct {\n", ifaceName, eventName)
	fmt.Fprintf(w, "proxy *%s\n", ifaceName)
	for _, arg := range e.Args {
		argName := toCamel(arg.Name)

		if arg.Description.Summary != "" {
			fmt.Fprintf(w, "// %s %s\n", argName, strings.Replace(arg.Description.Summary, "\n", " ", -1))
		}
		fmt.Fprint(w, comment(arg.Description.Text))
		switch arg.Type {
		case "object", "new_id":
			if arg.Interface != "" {
				argIface := trimName(arg.Interface)
				argIface = toCamel(argIface)

				fmt.Fprintf(w, "%s *%s\n", argName, argIface)
			} else {
				fmt.Fprintf(w, "%s runtime.Proxy\n", argName)
			}

		case "int", "uint", "fixed",
			"string", "array", "fd":
			fmt.Fprintf(w, "%s %s\n", argName, typeToGoTypeMap[arg.Type])
		}
	}
	fmt.Fprintf(w, "}\n")

	fmt.Fprintf(w, "// WaitFor%s: waits for %s%sEvent\n", eventName, ifaceName, eventName)
	fmt.Fprintf(w, "func (i *%s) WaitFor%s() %s%sEvent {\n", ifaceName, eventName, ifaceName, eventName)
	fmt.Fprintf(w, "c, ok := i.waitfor[\"%s\"]\n", eventName)
	fmt.Fprintf(w, "if !ok {\n")
	fmt.Fprintf(w, "c = make(chan runtime.Event)\n")
	fmt.Fprintf(w, "i.waitfor[\"%s\"] = c\n", eventName)
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "return (<-c).(%s%sEvent)\n", ifaceName, eventName)
	fmt.Fprintf(w, "}\n")

	// // Set handler
	// fmt.Fprintf(w, "// Handle%sOnce : sets handler for %s%sEvent\n", eventName, ifaceName, eventName)
	// fmt.Fprintf(w, "func (i *%s) Handle%sOnce() %s%sEvent {\n", ifaceName, eventName, ifaceName, eventName)
	// fmt.Fprintf(w, "oldHandler := i.%sHandler\n", eventNameLower)
	// fmt.Fprintf(w, "defer func() {i.%sHandler = oldHandler }()\n", eventNameLower)
	// fmt.Fprintf(w, "res := make(chan %s%sEvent)\n", ifaceName, eventName)
	// fmt.Fprintf(w, "i.%sHandler = func(evt %s%sEvent) {\n", eventNameLower, ifaceName, eventName)
	// fmt.Fprintf(w, "res <- evt\n")
	// fmt.Fprintf(w, "}\n")
	// fmt.Fprintf(w, "return <-res\n")
	// fmt.Fprintf(w, "}\n")
}

func writeEventDispatcher(w io.Writer, imports map[string]bool, ifaceName string, v Interface) {
	fmt.Fprintf(w, "func (i *%s) Dispatch(opcode uint32, fd int, data []byte) runtime.Event {\n", ifaceName)
	if len(v.Events) > 0 {
		fmt.Fprintf(w, "switch opcode {\n")
		for i, e := range v.Events {
			eventName := toCamel(e.Name)
			// eventNameLower := toLowerCamel(e.Name)

			// hasFd := false
			// for _, arg := range e.Args {
			// 	if arg.Type == "fd" {
			// 		hasFd = true
			// 		break
			// 	}
			// }

			fmt.Fprintf(w, "case %d:\n", i)
			// fmt.Fprintf(w, "if i.%sHandler == nil {\n", eventNameLower)
			// if hasFd {
			// 	imports["syscall"] = true
			// 	fmt.Fprintf(w, "if fd != -1 {\n")
			// 	fmt.Fprintf(w, "syscall.Close(fd)\n")
			// 	fmt.Fprintf(w, "}\n")
			// }
			// fmt.Fprintf(w, "return\n")
			// fmt.Fprintf(w, "}\n")

			fmt.Fprintf(w, "var e  %s%sEvent\n", ifaceName, eventName)
			fmt.Fprintf(w, "e.proxy = i\n")

			if len(e.Args) > 0 && (len(e.Args) != 1 || e.Args[0].Type != "fd") {
				fmt.Fprintf(w, "l := 0\n")
			}

			for _, arg := range e.Args {
				argName := toCamel(arg.Name)
				argNameLower := toLowerCamel(arg.Name)

				switch arg.Type {
				case "object", "new_id":
					if arg.Interface != "" {
						argIface := trimName(arg.Interface)
						argIface = toCamel(argIface)

						fmt.Fprintf(w, "e.%s = i.Context().GetProxy(runtime.Uint32(data[l :l+4])).(*%s)\n", argName, argIface)
					} else {
						fmt.Fprintf(w, "e.%s = i.Context().GetProxy(runtime.Uint32(data[l :l+4]))\n", argName)
					}
					fmt.Fprintf(w, "l += 4\n")

				case "fd":
					fmt.Fprintf(w, "e.%s = fd\n", argName)

				case "uint":
					fmt.Fprintf(w, "e.%s = runtime.Uint32(data[l : l+4])\n", argName)
					fmt.Fprintf(w, "l += 4\n")

				case "int":
					fmt.Fprintf(w, "e.%s = int32(runtime.Uint32(data[l : l+4]))\n", argName)
					fmt.Fprintf(w, "l += 4\n")

				case "fixed":
					fmt.Fprintf(w, "e.%s = runtime.Fixed(data[l : l+4])\n", argName)
					fmt.Fprintf(w, "l += 4\n")

				case "string":
					fmt.Fprintf(w, "%sLen := runtime.PaddedLen(int(runtime.Uint32(data[l : l+4])))\n", argNameLower)
					fmt.Fprintf(w, "l += 4\n")
					fmt.Fprintf(w, "e.%s = runtime.String(data[l : l+%sLen])\n", argName, argNameLower)
					fmt.Fprintf(w, "l += %sLen\n", argNameLower)

				case "array":
					fmt.Fprintf(w, "%sLen := int(runtime.Uint32(data[l : l+4]))\n", argNameLower)
					fmt.Fprintf(w, "l += 4\n")
					fmt.Fprintf(w, "e.%s = make([]byte, %sLen)\n", argName, argNameLower)
					fmt.Fprintf(w, "copy(e.%s, data[l:l+%sLen])\n", argName, argNameLower)
					fmt.Fprintf(w, "l += %sLen\n", argNameLower)
				}
			}

			fmt.Fprintf(w, "\nif c, ok := i.waitfor[\"%s\"]; ok {\n", eventName)
			fmt.Fprintf(w, "select {\n")
			fmt.Fprintf(w, "case c<-e:\n")
			fmt.Fprintf(w, "return nil\n")
			fmt.Fprintf(w, "default:\n")
			fmt.Fprintf(w, "delete(i.waitfor, \"%s\")\n", eventName)
			fmt.Fprintf(w, "}\n")
			fmt.Fprintf(w, "}\n")
			fmt.Fprintf(w, "return e\n")
		}
		fmt.Fprintf(w, "}\n")
	}
	fmt.Fprintf(w, "\nreturn nil\n")
	fmt.Fprintf(w, "}\n")
}

func toCamel(s string) string {
	s = strings.TrimPrefix(s, *prefix)
	s = strings.TrimSuffix(s, *suffix)

	s = strcase.ToCamel(s)
	return s
}

func toLowerCamel(s string) string {
	s = strcase.ToLowerCamel(s)
	if s == "map" {
		s = "_map"
	}
	return s
}

func comment(s string) string {
	sb := strings.Builder{}

	scanner := bufio.NewScanner(strings.NewReader(s))
	for scanner.Scan() {
		sb.WriteString("// ")
		sb.WriteString(strings.TrimSpace(scanner.Text()))
		sb.WriteString("\n")
	}

	return strings.TrimSuffix(sb.String(), "// \n")
}

func hasDestructor(v Interface) bool {
	for _, r := range v.Requests {
		if r.Type == "destructor" {
			return true
		}
	}

	return false
}
